PRAGMA foreign_keys=ON; BEGIN;
INSERT INTO Schools(id,name,code,principal_name,is_demo) VALUES (1,'آموزشگاه میرزا کوچک‌خان','DEMO-001','مدیر نمونه',1);
INSERT INTO AcademicYears(id,school_id,label,start_date,end_date,is_current) VALUES (1,1,'1405-1406','2026-09-23','2027-06-21',1);
INSERT INTO Users(id,school_id,username,password_hash,role_id,display_name) VALUES (1,1,'demo_admin','!DEMO-DISABLED!',1,'مدیر نمونه');
INSERT INTO Shifts(id,school_id,name) VALUES (1,1,'صبح');
INSERT INTO Subjects(id,school_id,name) VALUES (1,1,'ریاضی');
INSERT INTO Subjects(id,school_id,name) VALUES (2,1,'ادبیات فارسی');
INSERT INTO Subjects(id,school_id,name) VALUES (3,1,'علوم تجربی');
INSERT INTO Subjects(id,school_id,name) VALUES (4,1,'زبان انگلیسی');
INSERT INTO Subjects(id,school_id,name) VALUES (5,1,'عربی');
INSERT INTO Subjects(id,school_id,name) VALUES (6,1,'دین و زندگی');
INSERT INTO Subjects(id,school_id,name) VALUES (7,1,'مطالعات اجتماعی');
INSERT INTO Subjects(id,school_id,name) VALUES (8,1,'تربیت بدنی');
INSERT INTO Subjects(id,school_id,name) VALUES (9,1,'هنر');
INSERT INTO Subjects(id,school_id,name) VALUES (10,1,'کار و فناوری');
INSERT INTO Users(id,school_id,username,password_hash,role_id,display_name) VALUES (2,1,'demo_t1','!DEMO-DISABLED!',3,'احمد احمدی');
INSERT INTO Teachers(id,school_id,user_id,first_name,last_name,national_id,employee_id,mobile,primary_subject_id) VALUES (1,1,2,'احمد','احمدی','1000000001','E1001','09120001001',1);
INSERT INTO TeacherSubjects VALUES (1,1);
INSERT INTO Users(id,school_id,username,password_hash,role_id,display_name) VALUES (3,1,'demo_t2','!DEMO-DISABLED!',3,'رضا رضایی');
INSERT INTO Teachers(id,school_id,user_id,first_name,last_name,national_id,employee_id,mobile,primary_subject_id) VALUES (2,1,3,'رضا','رضایی','1000000011','E1002','09120001002',2);
INSERT INTO TeacherSubjects VALUES (2,2);
INSERT INTO Users(id,school_id,username,password_hash,role_id,display_name) VALUES (4,1,'demo_t3','!DEMO-DISABLED!',3,'مریم کریمی');
INSERT INTO Teachers(id,school_id,user_id,first_name,last_name,national_id,employee_id,mobile,primary_subject_id) VALUES (3,1,4,'مریم','کریمی','1000000028','E1003','09120001003',3);
INSERT INTO TeacherSubjects VALUES (3,3);
INSERT INTO Users(id,school_id,username,password_hash,role_id,display_name) VALUES (5,1,'demo_t4','!DEMO-DISABLED!',3,'زهرا حسینی');
INSERT INTO Teachers(id,school_id,user_id,first_name,last_name,national_id,employee_id,mobile,primary_subject_id) VALUES (4,1,5,'زهرا','حسینی','1000000036','E1004','09120001004',4);
INSERT INTO TeacherSubjects VALUES (4,4);
INSERT INTO Users(id,school_id,username,password_hash,role_id,display_name) VALUES (6,1,'demo_t5','!DEMO-DISABLED!',3,'علی موسوی');
INSERT INTO Teachers(id,school_id,user_id,first_name,last_name,national_id,employee_id,mobile,primary_subject_id) VALUES (5,1,6,'علی','موسوی','1000000044','E1005','09120001005',5);
INSERT INTO TeacherSubjects VALUES (5,5);
INSERT INTO Users(id,school_id,username,password_hash,role_id,display_name) VALUES (7,1,'demo_t6','!DEMO-DISABLED!',3,'فاطمه جعفری');
INSERT INTO Teachers(id,school_id,user_id,first_name,last_name,national_id,employee_id,mobile,primary_subject_id) VALUES (6,1,7,'فاطمه','جعفری','1000000052','E1006','09120001006',6);
INSERT INTO TeacherSubjects VALUES (6,6);
INSERT INTO Users(id,school_id,username,password_hash,role_id,display_name) VALUES (8,1,'demo_t7','!DEMO-DISABLED!',3,'حسین صادقی');
INSERT INTO Teachers(id,school_id,user_id,first_name,last_name,national_id,employee_id,mobile,primary_subject_id) VALUES (7,1,8,'حسین','صادقی','1000000060','E1007','09120001007',7);
INSERT INTO TeacherSubjects VALUES (7,7);
INSERT INTO Users(id,school_id,username,password_hash,role_id,display_name) VALUES (9,1,'demo_t8','!DEMO-DISABLED!',3,'سارا نوری');
INSERT INTO Teachers(id,school_id,user_id,first_name,last_name,national_id,employee_id,mobile,primary_subject_id) VALUES (8,1,9,'سارا','نوری','1000000079','E1008','09120001008',8);
INSERT INTO TeacherSubjects VALUES (8,8);
INSERT INTO Users(id,school_id,username,password_hash,role_id,display_name) VALUES (10,1,'demo_t9','!DEMO-DISABLED!',3,'محمد قاسمی');
INSERT INTO Teachers(id,school_id,user_id,first_name,last_name,national_id,employee_id,mobile,primary_subject_id) VALUES (9,1,10,'محمد','قاسمی','1000000087','E1009','09120001009',9);
INSERT INTO TeacherSubjects VALUES (9,9);
INSERT INTO Users(id,school_id,username,password_hash,role_id,display_name) VALUES (11,1,'demo_t10','!DEMO-DISABLED!',3,'نرگس اکبری');
INSERT INTO Teachers(id,school_id,user_id,first_name,last_name,national_id,employee_id,mobile,primary_subject_id) VALUES (10,1,11,'نرگس','اکبری','1000000095','E1010','09120001010',10);
INSERT INTO TeacherSubjects VALUES (10,10);
INSERT INTO Classes(id,school_id,academic_year_id,grade_level,section,room,shift_id) VALUES (1,1,1,7,'الف','1',1);
INSERT INTO Classes(id,school_id,academic_year_id,grade_level,section,room,shift_id) VALUES (2,1,1,7,'ب','2',1);
INSERT INTO Classes(id,school_id,academic_year_id,grade_level,section,room,shift_id) VALUES (3,1,1,8,'الف','3',1);
INSERT INTO Classes(id,school_id,academic_year_id,grade_level,section,room,shift_id) VALUES (4,1,1,8,'ب','4',1);
INSERT INTO Classes(id,school_id,academic_year_id,grade_level,section,room,shift_id) VALUES (5,1,1,9,'الف','5',1);
INSERT INTO Classes(id,school_id,academic_year_id,grade_level,section,room,shift_id) VALUES (6,1,1,9,'ب','6',1);
INSERT INTO BellSchedules(id,shift_id,period_no,kind,label,start_time,end_time) VALUES (1,1,NULL,'opening','زنگ شروع','07:30','07:30');
INSERT INTO BellSchedules(id,shift_id,period_no,kind,label,start_time,end_time) VALUES (2,1,1,'class','زنگ اول','07:30','08:15');
INSERT INTO BellSchedules(id,shift_id,period_no,kind,label,start_time,end_time) VALUES (3,1,NULL,'break','تنفس','08:15','08:30');
INSERT INTO BellSchedules(id,shift_id,period_no,kind,label,start_time,end_time) VALUES (4,1,2,'class','زنگ دوم','08:30','09:15');
INSERT INTO BellSchedules(id,shift_id,period_no,kind,label,start_time,end_time) VALUES (5,1,NULL,'break','تنفس','09:15','09:30');
INSERT INTO BellSchedules(id,shift_id,period_no,kind,label,start_time,end_time) VALUES (6,1,3,'class','زنگ سوم','09:30','10:15');
INSERT INTO BellSchedules(id,shift_id,period_no,kind,label,start_time,end_time) VALUES (7,1,NULL,'break','تنفس','10:15','10:30');
INSERT INTO BellSchedules(id,shift_id,period_no,kind,label,start_time,end_time) VALUES (8,1,4,'class','زنگ چهارم','10:30','11:15');
INSERT INTO BellSchedules(id,shift_id,period_no,kind,label,start_time,end_time) VALUES (9,1,NULL,'closing','زنگ پایان','11:15','11:15');
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (1,1,1,3,3,0,2,'1');
INSERT INTO TeacherClasses VALUES (3,1,3);
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (2,1,1,5,5,0,4,'1');
INSERT INTO TeacherClasses VALUES (5,1,5);
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (3,1,1,7,7,0,6,'1');
INSERT INTO TeacherClasses VALUES (7,1,7);
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (4,1,1,9,9,0,8,'1');
INSERT INTO TeacherClasses VALUES (9,1,9);
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (5,1,1,6,6,1,2,'1');
INSERT INTO TeacherClasses VALUES (6,1,6);
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (6,1,1,8,8,1,4,'1');
INSERT INTO TeacherClasses VALUES (8,1,8);
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (7,1,1,10,10,1,6,'1');
INSERT INTO TeacherClasses VALUES (10,1,10);
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (8,1,1,2,2,1,8,'1');
INSERT INTO TeacherClasses VALUES (2,1,2);
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (9,1,1,9,9,2,2,'1');
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (10,1,1,1,1,2,4,'1');
INSERT INTO TeacherClasses VALUES (1,1,1);
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (11,1,1,3,3,2,6,'1');
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (12,1,1,5,5,2,8,'1');
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (13,1,1,2,2,3,2,'1');
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (14,1,1,4,4,3,4,'1');
INSERT INTO TeacherClasses VALUES (4,1,4);
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (15,1,1,6,6,3,6,'1');
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (16,1,1,8,8,3,8,'1');
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (17,1,1,5,5,4,2,'1');
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (18,1,1,7,7,4,4,'1');
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (19,1,1,9,9,4,6,'1');
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (20,1,1,1,1,4,8,'1');
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (21,1,2,4,4,0,2,'2');
INSERT INTO TeacherClasses VALUES (4,2,4);
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (22,1,2,6,6,0,4,'2');
INSERT INTO TeacherClasses VALUES (6,2,6);
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (23,1,2,8,8,0,6,'2');
INSERT INTO TeacherClasses VALUES (8,2,8);
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (24,1,2,10,10,0,8,'2');
INSERT INTO TeacherClasses VALUES (10,2,10);
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (25,1,2,7,7,1,2,'2');
INSERT INTO TeacherClasses VALUES (7,2,7);
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (26,1,2,9,9,1,4,'2');
INSERT INTO TeacherClasses VALUES (9,2,9);
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (27,1,2,1,1,1,6,'2');
INSERT INTO TeacherClasses VALUES (1,2,1);
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (28,1,2,3,3,1,8,'2');
INSERT INTO TeacherClasses VALUES (3,2,3);
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (29,1,2,10,10,2,2,'2');
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (30,1,2,2,2,2,4,'2');
INSERT INTO TeacherClasses VALUES (2,2,2);
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (31,1,2,4,4,2,6,'2');
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (32,1,2,6,6,2,8,'2');
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (33,1,2,3,3,3,2,'2');
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (34,1,2,5,5,3,4,'2');
INSERT INTO TeacherClasses VALUES (5,2,5);
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (35,1,2,7,7,3,6,'2');
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (36,1,2,9,9,3,8,'2');
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (37,1,2,6,6,4,2,'2');
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (38,1,2,8,8,4,4,'2');
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (39,1,2,10,10,4,6,'2');
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (40,1,2,2,2,4,8,'2');
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (41,1,3,5,5,0,2,'3');
INSERT INTO TeacherClasses VALUES (5,3,5);
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (42,1,3,7,7,0,4,'3');
INSERT INTO TeacherClasses VALUES (7,3,7);
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (43,1,3,9,9,0,6,'3');
INSERT INTO TeacherClasses VALUES (9,3,9);
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (44,1,3,1,1,0,8,'3');
INSERT INTO TeacherClasses VALUES (1,3,1);
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (45,1,3,8,8,1,2,'3');
INSERT INTO TeacherClasses VALUES (8,3,8);
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (46,1,3,10,10,1,4,'3');
INSERT INTO TeacherClasses VALUES (10,3,10);
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (47,1,3,2,2,1,6,'3');
INSERT INTO TeacherClasses VALUES (2,3,2);
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (48,1,3,4,4,1,8,'3');
INSERT INTO TeacherClasses VALUES (4,3,4);
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (49,1,3,1,1,2,2,'3');
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (50,1,3,3,3,2,4,'3');
INSERT INTO TeacherClasses VALUES (3,3,3);
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (51,1,3,5,5,2,6,'3');
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (52,1,3,7,7,2,8,'3');
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (53,1,3,4,4,3,2,'3');
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (54,1,3,6,6,3,4,'3');
INSERT INTO TeacherClasses VALUES (6,3,6);
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (55,1,3,8,8,3,6,'3');
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (56,1,3,10,10,3,8,'3');
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (57,1,3,7,7,4,2,'3');
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (58,1,3,9,9,4,4,'3');
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (59,1,3,1,1,4,6,'3');
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (60,1,3,3,3,4,8,'3');
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (61,1,4,6,6,0,2,'4');
INSERT INTO TeacherClasses VALUES (6,4,6);
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (62,1,4,8,8,0,4,'4');
INSERT INTO TeacherClasses VALUES (8,4,8);
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (63,1,4,10,10,0,6,'4');
INSERT INTO TeacherClasses VALUES (10,4,10);
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (64,1,4,2,2,0,8,'4');
INSERT INTO TeacherClasses VALUES (2,4,2);
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (65,1,4,9,9,1,2,'4');
INSERT INTO TeacherClasses VALUES (9,4,9);
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (66,1,4,1,1,1,4,'4');
INSERT INTO TeacherClasses VALUES (1,4,1);
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (67,1,4,3,3,1,6,'4');
INSERT INTO TeacherClasses VALUES (3,4,3);
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (68,1,4,5,5,1,8,'4');
INSERT INTO TeacherClasses VALUES (5,4,5);
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (69,1,4,2,2,2,2,'4');
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (70,1,4,4,4,2,4,'4');
INSERT INTO TeacherClasses VALUES (4,4,4);
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (71,1,4,6,6,2,6,'4');
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (72,1,4,8,8,2,8,'4');
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (73,1,4,5,5,3,2,'4');
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (74,1,4,7,7,3,4,'4');
INSERT INTO TeacherClasses VALUES (7,4,7);
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (75,1,4,9,9,3,6,'4');
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (76,1,4,1,1,3,8,'4');
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (77,1,4,8,8,4,2,'4');
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (78,1,4,10,10,4,4,'4');
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (79,1,4,2,2,4,6,'4');
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (80,1,4,4,4,4,8,'4');
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (81,1,5,7,7,0,2,'5');
INSERT INTO TeacherClasses VALUES (7,5,7);
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (82,1,5,9,9,0,4,'5');
INSERT INTO TeacherClasses VALUES (9,5,9);
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (83,1,5,1,1,0,6,'5');
INSERT INTO TeacherClasses VALUES (1,5,1);
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (84,1,5,3,3,0,8,'5');
INSERT INTO TeacherClasses VALUES (3,5,3);
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (85,1,5,10,10,1,2,'5');
INSERT INTO TeacherClasses VALUES (10,5,10);
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (86,1,5,2,2,1,4,'5');
INSERT INTO TeacherClasses VALUES (2,5,2);
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (87,1,5,4,4,1,6,'5');
INSERT INTO TeacherClasses VALUES (4,5,4);
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (88,1,5,6,6,1,8,'5');
INSERT INTO TeacherClasses VALUES (6,5,6);
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (89,1,5,3,3,2,2,'5');
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (90,1,5,5,5,2,4,'5');
INSERT INTO TeacherClasses VALUES (5,5,5);
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (91,1,5,7,7,2,6,'5');
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (92,1,5,9,9,2,8,'5');
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (93,1,5,6,6,3,2,'5');
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (94,1,5,8,8,3,4,'5');
INSERT INTO TeacherClasses VALUES (8,5,8);
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (95,1,5,10,10,3,6,'5');
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (96,1,5,2,2,3,8,'5');
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (97,1,5,9,9,4,2,'5');
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (98,1,5,1,1,4,4,'5');
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (99,1,5,3,3,4,6,'5');
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (100,1,5,5,5,4,8,'5');
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (101,1,6,8,8,0,2,'6');
INSERT INTO TeacherClasses VALUES (8,6,8);
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (102,1,6,10,10,0,4,'6');
INSERT INTO TeacherClasses VALUES (10,6,10);
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (103,1,6,2,2,0,6,'6');
INSERT INTO TeacherClasses VALUES (2,6,2);
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (104,1,6,4,4,0,8,'6');
INSERT INTO TeacherClasses VALUES (4,6,4);
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (105,1,6,1,1,1,2,'6');
INSERT INTO TeacherClasses VALUES (1,6,1);
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (106,1,6,3,3,1,4,'6');
INSERT INTO TeacherClasses VALUES (3,6,3);
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (107,1,6,5,5,1,6,'6');
INSERT INTO TeacherClasses VALUES (5,6,5);
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (108,1,6,7,7,1,8,'6');
INSERT INTO TeacherClasses VALUES (7,6,7);
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (109,1,6,4,4,2,2,'6');
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (110,1,6,6,6,2,4,'6');
INSERT INTO TeacherClasses VALUES (6,6,6);
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (111,1,6,8,8,2,6,'6');
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (112,1,6,10,10,2,8,'6');
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (113,1,6,7,7,3,2,'6');
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (114,1,6,9,9,3,4,'6');
INSERT INTO TeacherClasses VALUES (9,6,9);
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (115,1,6,1,1,3,6,'6');
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (116,1,6,3,3,3,8,'6');
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (117,1,6,10,10,4,2,'6');
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (118,1,6,2,2,4,4,'6');
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (119,1,6,4,4,4,6,'6');
INSERT INTO Timetables(id,academic_year_id,class_id,teacher_id,subject_id,day_of_week,bell_schedule_id,room) VALUES (120,1,6,6,6,4,8,'6');
INSERT INTO Students(id,school_id,student_code,national_id,first_name,last_name,father_name,class_id,parent_phone) VALUES (1,1,'S5001','2000000010','امیر','محمدی','پدر نمونه','1','09350000001');
INSERT INTO Students(id,school_id,student_code,national_id,first_name,last_name,father_name,class_id,parent_phone) VALUES (2,1,'S5002','2000000029','امیر','اسدی','پدر نمونه','1','09350000002');
INSERT INTO Students(id,school_id,student_code,national_id,first_name,last_name,father_name,class_id,parent_phone) VALUES (3,1,'S5003','2000000037','امیر','رستمی','پدر نمونه','1','09350000003');
INSERT INTO Students(id,school_id,student_code,national_id,first_name,last_name,father_name,class_id,parent_phone) VALUES (4,1,'S5004','2000000045','امیر','یوسفی','پدر نمونه','1','09350000004');
INSERT INTO Students(id,school_id,student_code,national_id,first_name,last_name,father_name,class_id,parent_phone) VALUES (5,1,'S5005','2000000053','امیر','کاظمی','پدر نمونه','1','09350000005');
INSERT INTO Students(id,school_id,student_code,national_id,first_name,last_name,father_name,class_id,parent_phone) VALUES (6,1,'S5006','2000000061','آرین','محمدی','پدر نمونه','2','09350000006');
INSERT INTO Students(id,school_id,student_code,national_id,first_name,last_name,father_name,class_id,parent_phone) VALUES (7,1,'S5007','2000000071','آرین','اسدی','پدر نمونه','2','09350000007');
INSERT INTO Students(id,school_id,student_code,national_id,first_name,last_name,father_name,class_id,parent_phone) VALUES (8,1,'S5008','2000000088','آرین','رستمی','پدر نمونه','2','09350000008');
INSERT INTO Students(id,school_id,student_code,national_id,first_name,last_name,father_name,class_id,parent_phone) VALUES (9,1,'S5009','2000000096','آرین','یوسفی','پدر نمونه','2','09350000009');
INSERT INTO Students(id,school_id,student_code,national_id,first_name,last_name,father_name,class_id,parent_phone) VALUES (10,1,'S5010','2000000101','آرین','کاظمی','پدر نمونه','2','09350000010');
INSERT INTO Students(id,school_id,student_code,national_id,first_name,last_name,father_name,class_id,parent_phone) VALUES (11,1,'S5011','2000000118','پارسا','محمدی','پدر نمونه','3','09350000011');
INSERT INTO Students(id,school_id,student_code,national_id,first_name,last_name,father_name,class_id,parent_phone) VALUES (12,1,'S5012','2000000126','پارسا','اسدی','پدر نمونه','3','09350000012');
INSERT INTO Students(id,school_id,student_code,national_id,first_name,last_name,father_name,class_id,parent_phone) VALUES (13,1,'S5013','2000000134','پارسا','رستمی','پدر نمونه','3','09350000013');
INSERT INTO Students(id,school_id,student_code,national_id,first_name,last_name,father_name,class_id,parent_phone) VALUES (14,1,'S5014','2000000142','پارسا','یوسفی','پدر نمونه','3','09350000014');
INSERT INTO Students(id,school_id,student_code,national_id,first_name,last_name,father_name,class_id,parent_phone) VALUES (15,1,'S5015','2000000150','پارسا','کاظمی','پدر نمونه','3','09350000015');
INSERT INTO Students(id,school_id,student_code,national_id,first_name,last_name,father_name,class_id,parent_phone) VALUES (16,1,'S5016','2000000169','سینا','محمدی','پدر نمونه','4','09350000016');
INSERT INTO Students(id,school_id,student_code,national_id,first_name,last_name,father_name,class_id,parent_phone) VALUES (17,1,'S5017','2000000177','سینا','اسدی','پدر نمونه','4','09350000017');
INSERT INTO Students(id,school_id,student_code,national_id,first_name,last_name,father_name,class_id,parent_phone) VALUES (18,1,'S5018','2000000185','سینا','رستمی','پدر نمونه','4','09350000018');
INSERT INTO Students(id,school_id,student_code,national_id,first_name,last_name,father_name,class_id,parent_phone) VALUES (19,1,'S5019','2000000193','سینا','یوسفی','پدر نمونه','4','09350000019');
INSERT INTO Students(id,school_id,student_code,national_id,first_name,last_name,father_name,class_id,parent_phone) VALUES (20,1,'S5020','2000000207','سینا','کاظمی','پدر نمونه','4','09350000020');
INSERT INTO Students(id,school_id,student_code,national_id,first_name,last_name,father_name,class_id,parent_phone) VALUES (21,1,'S5021','2000000215','نیما','محمدی','پدر نمونه','5','09350000021');
INSERT INTO Students(id,school_id,student_code,national_id,first_name,last_name,father_name,class_id,parent_phone) VALUES (22,1,'S5022','2000000223','نیما','اسدی','پدر نمونه','5','09350000022');
INSERT INTO Students(id,school_id,student_code,national_id,first_name,last_name,father_name,class_id,parent_phone) VALUES (23,1,'S5023','2000000231','نیما','رستمی','پدر نمونه','5','09350000023');
INSERT INTO Students(id,school_id,student_code,national_id,first_name,last_name,father_name,class_id,parent_phone) VALUES (24,1,'S5024','2000000241','نیما','یوسفی','پدر نمونه','5','09350000024');
INSERT INTO Students(id,school_id,student_code,national_id,first_name,last_name,father_name,class_id,parent_phone) VALUES (25,1,'S5025','2000000258','نیما','کاظمی','پدر نمونه','5','09350000025');
INSERT INTO Students(id,school_id,student_code,national_id,first_name,last_name,father_name,class_id,parent_phone) VALUES (26,1,'S5026','2000000266','کیان','محمدی','پدر نمونه','6','09350000026');
INSERT INTO Students(id,school_id,student_code,national_id,first_name,last_name,father_name,class_id,parent_phone) VALUES (27,1,'S5027','2000000274','کیان','اسدی','پدر نمونه','6','09350000027');
INSERT INTO Students(id,school_id,student_code,national_id,first_name,last_name,father_name,class_id,parent_phone) VALUES (28,1,'S5028','2000000282','کیان','رستمی','پدر نمونه','6','09350000028');
INSERT INTO Students(id,school_id,student_code,national_id,first_name,last_name,father_name,class_id,parent_phone) VALUES (29,1,'S5029','2000000290','کیان','یوسفی','پدر نمونه','6','09350000029');
INSERT INTO Students(id,school_id,student_code,national_id,first_name,last_name,father_name,class_id,parent_phone) VALUES (30,1,'S5030','2000000304','کیان','کاظمی','پدر نمونه','6','09350000030');
UPDATE Settings SET value='demo' WHERE key='data_mode';
COMMIT;
